### ISSUE TITLE
Inputs with a Fixed Width on Larger Screens

### ISSUE THREAD

**Issue by chrsmendes** [chrsmendes/game-score#22]
Currently, all inputs have a fixed width of 320px on larger screens. Instead, they should adjust to fit the size of their parent container, rather than being set to 20em:  

```css
.input {
    width: 100%;
    /* max-width: 20rem; */
    max-width: 100%;
}
```
